<script setup lang="ts">
import AppIcon from '@/Components/AppIcon.vue';import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';import{Head,Link,router}from'@inertiajs/vue3';import{reactive}from'vue';
const props=defineProps<{users:any;filters:any;roles:string[];stats:any}>();const filters=reactive({...props.filters});const apply=()=>router.get(route('users.index'),filters,{preserveState:true,replace:true});const roleLabels:any={superadmin:'Super administrateur',secretaire:'Secrétaire',etudiant:'Étudiant'};const remove=(user:any)=>{if(confirm(`Supprimer définitivement le compte de ${user.name} ?`))router.delete(route('users.destroy',user.id),{preserveScroll:true});};
</script>
<template><Head title="Utilisateurs"/><AuthenticatedLayout><template #header><div class="flex items-end justify-between gap-4"><div><p class="dw-page-kicker">Administration</p><h1 class="dw-page-title">Utilisateurs</h1><p class="dw-page-description">Gérez les comptes, rôles et accès à l’application.</p></div><Link :href="route('users.create')" class="dw-btn-primary">Nouvel utilisateur</Link></div></template>
<div v-if="$page.props.flash?.success" class="mb-5 rounded-md bg-emerald-50 p-4 text-sm font-bold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{{$page.props.flash.success}}</div><div v-if="$page.props.errors?.user" class="mb-5 rounded-md bg-red-50 p-4 text-sm font-bold text-red-700 dark:bg-red-950 dark:text-red-300">{{$page.props.errors.user}}</div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div v-for="metric in [{label:'Comptes',value:stats.total},{label:'Actifs',value:stats.active},{label:'Suspendus',value:stats.suspended},{label:'Administrateurs',value:stats.administrators}]" :key="metric.label" class="dw-card p-5"><strong class="text-2xl text-slate-700 dark:text-white">{{metric.value}}</strong><p class="mt-1 text-xs text-slate-500">{{metric.label}}</p></div></div>
<section class="dw-card mt-6 p-5"><form class="flex flex-col gap-3 md:flex-row" @submit.prevent="apply"><div class="relative flex-1"><AppIcon name="search" class="absolute start-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500 dark:text-slate-400"/><input v-model="filters.search" class="dw-field ps-11" placeholder="Nom ou adresse e-mail…"/></div><select v-model="filters.role" class="dw-field md:w-52"><option value="">Tous les rôles</option><option v-for="role in roles" :key="role" :value="role">{{roleLabels[role]||role}}</option></select><select v-model="filters.status" class="dw-field md:w-44"><option value="">Tous les statuts</option><option value="active">Actifs</option><option value="suspended">Suspendus</option></select><button class="dw-btn-primary">Filtrer</button></form></section>
<section class="dw-card mt-6 overflow-x-auto"><table class="dw-table min-w-[800px]"><thead><tr><th class="p-4 text-start">Utilisateur</th><th class="p-4 text-start">Rôle</th><th class="p-4 text-start">Statut</th><th class="p-4 text-start">Création</th><th class="w-28 p-4 text-center">Actions</th></tr></thead><tbody><tr v-for="user in users.data" :key="user.id"><td class="p-4"><strong class="text-sm text-slate-700 dark:text-slate-200">{{user.name}}</strong><p class="mt-1 text-xs text-slate-500 dark:text-slate-400">{{user.email}}</p></td><td class="p-4"><span class="rounded bg-primary-50 px-2.5 py-1 text-xs font-bold text-primary-700 dark:bg-primary-950 dark:text-primary-300">{{roleLabels[user.roles[0]?.name]||user.roles[0]?.name||'Sans rôle'}}</span></td><td class="p-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold" :class="user.is_active?'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300':'bg-red-50 text-red-700 dark:bg-red-950 dark:text-red-300'">{{user.is_active?'Actif':'Suspendu'}}</span></td><td class="p-4 text-sm text-slate-500">{{new Date(user.created_at).toLocaleDateString('fr-FR')}}</td><td class="p-3"><div class="flex justify-center gap-1"><Link :href="route('users.edit',user.id)" class="inline-flex h-9 w-9 items-center justify-center rounded-md text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950" title="Modifier" :aria-label="`Modifier ${user.name}`"><AppIcon name="edit" class="h-4 w-4"/></Link><button class="inline-flex h-9 w-9 items-center justify-center rounded-md text-red-600 hover:bg-red-50 dark:hover:bg-red-950" title="Supprimer" :aria-label="`Supprimer ${user.name}`" @click="remove(user)"><AppIcon name="trash" class="h-4 w-4"/></button></div></td></tr><tr v-if="!users.data.length"><td colspan="5" class="p-12 text-center text-slate-500 dark:text-slate-400">Aucun utilisateur trouvé.</td></tr></tbody></table></section>
<div v-if="users.links?.length>3" class="mt-5 flex justify-center gap-1"><Link v-for="link in users.links" :key="link.label" :href="link.url||'#'" class="rounded-md border px-3 py-2 text-xs font-semibold transition-colors" :class="link.active?'border-primary-600 bg-primary-600 text-white shadow-sm':!link.url?'pointer-events-none border-gray-200 text-slate-400 dark:border-gray-900 dark:text-slate-600':'border-gray-300 bg-white text-slate-600 hover:border-primary-300 hover:text-primary-600 dark:border-gray-800 dark:bg-gray-950 dark:text-slate-300 dark:hover:border-primary-700 dark:hover:text-primary-400'" v-html="link.label"/></div></AuthenticatedLayout></template>
