<script setup lang="ts">
import InputError from '@/Components/InputError.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

defineProps<{ imports: { data: Array<{ id: number; original_filename: string; status: string; total_rows: number; valid_rows: number; error_rows: number; created_at: string; uploader: { name: string } }> } }>();
const form = useForm<{ file: File | null }>({ file: null });
const submit = () => form.post(route('student-imports.store'), { forceFormData: true });
</script>

<template><Head title="Imports étudiants"/><AuthenticatedLayout><template #header><div><Link :href="route('students.index')" class="text-xs font-bold text-primary-600">← Retour aux étudiants</Link><h1 class="mt-2 font-heading text-2xl font-bold text-slate-800">Importer des étudiants</h1><p class="mt-2 text-sm text-slate-500">Formats Excel ou CSV, avec contrôle obligatoire avant intégration.</p></div></template>
<section class="dw-card p-5 sm:p-6"><h2 class="font-heading font-bold text-slate-800">Nouveau fichier</h2><p class="mt-2 text-sm text-slate-500">Colonnes reconnues : matricule, nom, prénom, sexe, code_redoublement, date_naissance, nationalite, telephone, adresse, niveau, parcours, annee_universitaire et email.</p><form class="mt-5 flex flex-col gap-3 sm:flex-row" @submit.prevent="submit"><input type="file" accept=".xlsx,.xls,.csv" class="block flex-1 rounded-md border border-slate-300 p-2 text-sm dark:border-slate-700" required @change="form.file = ($event.target as HTMLInputElement).files?.[0] || null"/><button :disabled="form.processing" class="rounded-md bg-primary-600 px-6 py-3 text-sm font-bold text-white disabled:opacity-50">Analyser le fichier</button></form><InputError class="mt-2" :message="form.errors.file"/></section>
<section class="dw-card mt-6 overflow-hidden"><div class="border-b border-slate-100 p-5"><h2 class="font-heading font-bold text-slate-800">Historique des imports</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-400"><tr><th class="p-4 text-start">Fichier</th><th class="p-4 text-start">Importé par</th><th class="p-4">Lignes</th><th class="p-4">Valides</th><th class="p-4">Erreurs</th><th class="p-4"></th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="item in imports.data" :key="item.id"><td class="p-4"><p class="font-semibold text-slate-700">{{ item.original_filename }}</p><p class="mt-1 text-xs text-slate-400">{{ item.status }}</p></td><td class="p-4">{{ item.uploader.name }}</td><td class="p-4 text-center">{{ item.total_rows }}</td><td class="p-4 text-center text-emerald-600">{{ item.valid_rows }}</td><td class="p-4 text-center text-red-600">{{ item.error_rows }}</td><td class="p-4 text-end"><Link :href="route('student-imports.show', item.id)" class="text-xs font-bold text-primary-600">Consulter</Link></td></tr><tr v-if="!imports.data.length"><td colspan="6" class="p-10 text-center text-slate-400">Aucun import.</td></tr></tbody></table></div></section>
</AuthenticatedLayout></template>
