<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router } from '@inertiajs/vue3';
type Row = { id: number; row_number: number; status: string; normalized_data: Record<string,string|null>; errors?: string[] };
const props = defineProps<{ importBatch: { id: number; original_filename: string; sheet_name?: string; status: string; total_rows: number; valid_rows: number; error_rows: number; imported_rows: number }; rows: { data: Row[] }; canCommit: boolean }>();
const commit = () => { if (confirm(`Importer ${props.importBatch.valid_rows} ligne(s) valide(s) ?`)) router.post(route('student-imports.commit', props.importBatch.id)); };
</script>
<template><Head title="Contrôle d’import"/><AuthenticatedLayout><template #header><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link :href="route('student-imports.index')" class="text-xs font-bold text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300">← Historique</Link><h1 class="dw-page-title mt-2">Contrôle de l’import</h1><p class="dw-page-description">{{ importBatch.original_filename }} · feuille {{ importBatch.sheet_name || 'active' }}</p></div><button v-if="canCommit && ['ready','needs_review'].includes(importBatch.status) && importBatch.valid_rows" class="dw-btn-primary" @click="commit">Valider les lignes correctes</button></div></template>
<div v-if="$page.props.flash?.success" class="mb-5 rounded-md bg-emerald-50 p-4 text-sm font-semibold text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{{ $page.props.flash.success }}</div><div class="mb-6 grid gap-4 sm:grid-cols-4"><div class="dw-card p-4"><p class="text-xs text-slate-500 dark:text-slate-400">Total</p><strong class="mt-1 block text-xl text-slate-800">{{ importBatch.total_rows }}</strong></div><div class="dw-card p-4"><p class="text-xs text-slate-500 dark:text-slate-400">Valides</p><strong class="mt-1 block text-xl text-emerald-600">{{ importBatch.valid_rows }}</strong></div><div class="dw-card p-4"><p class="text-xs text-slate-500 dark:text-slate-400">Erreurs</p><strong class="mt-1 block text-xl text-red-600">{{ importBatch.error_rows }}</strong></div><div class="dw-card p-4"><p class="text-xs text-slate-500 dark:text-slate-400">Importées</p><strong class="mt-1 block text-xl text-primary-600">{{ importBatch.imported_rows }}</strong></div></div>
<section class="dw-card overflow-x-auto"><table class="dw-table min-w-[950px] text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:text-slate-400"><tr><th class="p-4">Ligne</th><th class="p-4 text-start">Matricule</th><th class="p-4 text-start">Nom et prénom</th><th class="p-4 text-start">Naissance</th><th class="p-4 text-start">Contact</th><th class="p-4 text-start">Résultat</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="row in rows.data" :key="row.id"><td class="p-4 text-center font-mono">{{ row.row_number }}</td><td class="p-4 font-mono">{{ row.normalized_data?.academic_number || '—' }}</td><td class="p-4 font-semibold">{{ row.normalized_data?.last_name }} {{ row.normalized_data?.first_name }}</td><td class="p-4">{{ row.normalized_data?.birth_date || '—' }}</td><td class="p-4">{{ row.normalized_data?.phone || '—' }}</td><td class="p-4"><span v-if="row.status === 'valid'" class="text-xs font-bold text-emerald-600">Valide</span><span v-else-if="row.status === 'imported'" class="text-xs font-bold text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300">Importée</span><ul v-else class="list-disc ps-4 text-xs text-red-600"><li v-for="error in row.errors" :key="error">{{ error }}</li></ul></td></tr></tbody></table></section>
</AuthenticatedLayout></template>
