<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Rapport des présences — EDSP</title><style>
@page{margin:14mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,Arial,sans-serif;color:#243b53;font-size:10px;margin:0}h1{font-size:20px;margin:0 0 4px;color:#1e293b}.subtitle{color:#64748b;margin:0}.header{display:flex;justify-content:space-between;border-bottom:2px solid #6576ff;padding-bottom:10px;margin-bottom:14px}.meta{text-align:right;color:#64748b}.filters{background:#f5f7ff;border:1px solid #dbe1ff;padding:8px;margin-bottom:12px}table{width:100%;border-collapse:collapse}th{background:#eef2ff;color:#526484;text-transform:uppercase;font-size:8px;text-align:left;padding:7px;border:1px solid #dbe2ea}td{padding:7px;border:1px solid #dbe2ea;vertical-align:top}.active{color:#059669;font-weight:bold}.closed{color:#64748b}.footer{margin-top:12px;color:#94a3b8;font-size:8px;text-align:right}@media print{.no-print{display:none!important}body{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style></head><body>
<div class="no-print" style="text-align:right;margin-bottom:12px"><button onclick="window.print()" style="padding:8px 14px">Imprimer</button></div>
<div class="header"><div><h1>Rapport des présences</h1><p class="subtitle">Bibliothèque EDSP — Université de Mahajanga</p></div><div class="meta">Généré le {{ now()->format('d/m/Y à H:i') }}<br>{{ $visits->count() }} présence(s)</div></div>
<div class="filters"><strong>Périmètre :</strong> {{ $filters['from'] ? 'du '.\Carbon\Carbon::parse($filters['from'])->format('d/m/Y') : 'depuis le début' }} {{ $filters['to'] ? 'au '.\Carbon\Carbon::parse($filters['to'])->format('d/m/Y') : '' }} · Statut : {{ $filters['status'] === 'active' ? 'Présents' : ($filters['status'] === 'closed' ? 'Sortis' : 'Tous') }} {{ $filters['search'] ? '· Recherche : '.$filters['search'] : '' }}</div>
<table><thead><tr><th>N° présence</th><th>Étudiant</th><th>N° bibliothèque</th><th>Matricule</th><th>Entrée</th><th>Sortie</th><th>Durée</th><th>Consult.</th><th>Statut</th></tr></thead><tbody>
@forelse($visits as $visit)<tr><td>{{ $visit->visit_number }}</td><td><strong>{{ $visit->student->last_name }} {{ $visit->student->first_name }}</strong></td><td>{{ $visit->student->registration_number }}</td><td>{{ $visit->student->academic_number ?: '—' }}</td><td>{{ $visit->checked_in_at->format('d/m/Y H:i') }}</td><td>{{ $visit->checked_out_at?->format('d/m/Y H:i') ?: '—' }}</td><td>@php($minutes=(int)$visit->checked_in_at->diffInMinutes($visit->checked_out_at ?? now())){{ intdiv($minutes,60) }} h {{ $minutes%60 }} min</td><td>{{ $visit->consultation_sessions_count }}</td><td class="{{ $visit->checked_out_at?'closed':'active' }}">{{ $visit->checked_out_at?'Sorti':'Présent' }}</td></tr>@empty<tr><td colspan="9" style="text-align:center">Aucune présence pour ces filtres.</td></tr>@endforelse
</tbody></table><div class="footer">Document de contrôle interne — Bibliothèque EDSP</div></body></html>
