<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router, usePage } from '@inertiajs/vue3';
defineProps<{copies:{data:any[]};conditionLabels:Record<string,string>;statusLabels:Record<string,string>}>();
const page=usePage();
const canUpdate=page.props.auth.permissions.includes('copies.update');
const canDelete=page.props.auth.permissions.includes('catalog.manage');
const remove=(copy:any)=>{if(confirm(`Supprimer définitivement ${copy.inventory_number} ?`))router.delete(route('copies.destroy',copy.id));};
const statusClass:Record<string,string>={available:'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300',in_consultation:'bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300',borrowed:'bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300',damaged:'bg-orange-50 text-orange-700',lost:'bg-red-50 text-red-700',archived:'bg-slate-100 text-slate-600'};
</script>
<template><Head title="Exemplaires"/><AuthenticatedLayout><template #header><div class="flex items-end justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-primary-600">Inventaire</p><h1 class="mt-1 font-heading text-2xl font-bold text-slate-800">Exemplaires physiques</h1><p class="mt-2 text-sm text-slate-500">Chaque exemplaire possède son numéro, son emplacement, son état et son statut.</p></div><Link :href="route('copies.create')" class="rounded-md bg-primary-600 px-4 py-2.5 text-sm font-bold text-white">Nouvel exemplaire</Link></div></template><div v-if="$page.props.flash?.success" class="mb-4 rounded-md bg-emerald-50 p-3 text-sm text-emerald-700">{{$page.props.flash.success}}</div><div v-if="$page.props.errors?.copy" class="mb-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{{$page.props.errors.copy}}</div><section class="dw-card overflow-x-auto"><table class="w-full min-w-[1100px] text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-400"><tr><th class="p-4 text-start">N° d’enregistrement</th><th class="p-4 text-start">Ouvrage</th><th class="p-4 text-start">Emplacement</th><th class="p-4 text-start">État</th><th class="p-4 text-start">Statut</th><th class="p-4 text-end">Actions</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="copy in copies.data" :key="copy.id"><td class="p-4 font-mono font-bold text-primary-700">{{copy.inventory_number}}</td><td class="p-4 font-semibold text-slate-700">{{copy.book.title}}</td><td class="p-4">{{copy.location?`${copy.location.name} · ${copy.location.code}`:'Non affecté'}}</td><td class="p-4">{{conditionLabels[copy.condition]}}</td><td class="p-4"><span :class="statusClass[copy.status]" class="rounded-full px-2.5 py-1 text-xs font-bold">{{statusLabels[copy.status]}}</span></td><td class="p-4"><div class="flex justify-end gap-3"><a :href="route('copies.print',copy.id)" target="_blank" class="text-xs font-bold text-primary-600">Imprimer</a><Link v-if="canUpdate" :href="route('copies.edit',copy.id)" class="text-xs font-bold text-amber-600">Modifier</Link><button v-if="canDelete" class="text-xs font-bold text-red-600" @click="remove(copy)">Supprimer</button></div></td></tr><tr v-if="!copies.data.length"><td colspan="6" class="p-12 text-center text-slate-400">Aucun exemplaire enregistré.</td></tr></tbody></table></section></AuthenticatedLayout></template>
