<script setup lang="ts">
import InputError from '@/Components/InputError.vue';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router, useForm } from '@inertiajs/vue3';
defineProps<{ imports: { data: any[] }; referenceFiles: string[] }>();
const form = useForm<{ file: File | null }>({ file: null });
const upload = () => form.post(route('book-imports.store'), { forceFormData: true });
const reference = (filename: string) => router.post(route('book-imports.reference'), { filename });
</script>
<template><Head title="Imports ouvrages"/><AuthenticatedLayout><template #header><div><Link :href="route('books.index')" class="text-xs font-bold text-primary-600">← Retour aux ouvrages</Link><h1 class="mt-2 font-heading text-2xl font-bold text-slate-800">Importer les ouvrages</h1><p class="mt-2 text-sm text-slate-500">Analyse des catégories, titres, éditions, auteurs et quantités avant création.</p></div></template><div class="grid gap-6 xl:grid-cols-2"><section class="dw-card p-5"><h2 class="font-heading font-bold text-slate-800">Envoyer un classeur</h2><form class="mt-4 space-y-3" @submit.prevent="upload"><input type="file" accept=".xlsx,.xls,.csv" class="block w-full rounded-md border border-slate-300 p-2 text-sm dark:border-slate-700" required @change="form.file=($event.target as HTMLInputElement).files?.[0]||null"/><InputError :message="form.errors.file"/><button class="w-full rounded-md bg-primary-600 px-5 py-3 text-sm font-bold text-white">Analyser</button></form></section><section class="dw-card p-5"><h2 class="font-heading font-bold text-slate-800">Fichiers de référence privés</h2><p class="mt-2 text-sm text-slate-500">Classeurs détectés dans storage/app/imports/reference.</p><div class="mt-4 space-y-2"><button v-for="file in referenceFiles" :key="file" class="flex w-full items-center justify-between gap-4 rounded-md border border-slate-200 p-3 text-start text-sm hover:border-primary-300 dark:border-slate-700" @click="reference(file)"><span class="min-w-0 truncate font-semibold">{{file}}</span><span class="text-xs font-bold text-primary-600">Analyser</span></button><p v-if="!referenceFiles.length" class="text-sm text-slate-400">Aucun fichier détecté.</p></div></section></div><section class="dw-card mt-6 overflow-x-auto"><table class="w-full min-w-[700px] text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-400"><tr><th class="p-4 text-start">Fichier</th><th class="p-4">Ouvrages</th><th class="p-4">Valides</th><th class="p-4">À corriger</th><th></th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="item in imports.data" :key="item.id"><td class="p-4 font-semibold">{{item.original_filename}}</td><td class="p-4 text-center">{{item.total_rows}}</td><td class="p-4 text-center text-emerald-600">{{item.valid_rows}}</td><td class="p-4 text-center text-red-600">{{item.error_rows}}</td><td class="p-4 text-end"><Link :href="route('book-imports.show',item.id)" class="text-xs font-bold text-primary-600">Contrôler</Link></td></tr><tr v-if="!imports.data.length"><td colspan="5" class="p-10 text-center text-slate-400">Aucun import d’ouvrages.</td></tr></tbody></table></section></AuthenticatedLayout></template>
