<?php
namespace App\Http\Controllers;
use App\Models\User;use Illuminate\Database\Eloquent\Builder;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Illuminate\Validation\Rules\Password;use Illuminate\Validation\ValidationException;use Inertia\Inertia;use Inertia\Response;use Spatie\Permission\Models\Role;
class UserController extends Controller{
public function index(Request $request):Response{$search=trim($request->string('search')->toString());$status=$request->string('status')->toString();$role=$request->string('role')->toString();$users=User::query()->with('roles:id,name')->when($search,fn(Builder $q)=>$q->where(fn(Builder $n)=>$n->where('name','like',"%{$search}%")->orWhere('email','like',"%{$search}%")))->when($status==='active',fn(Builder $q)=>$q->where('is_active',true))->when($status==='suspended',fn(Builder $q)=>$q->where('is_active',false))->when($role,fn(Builder $q)=>$q->role($role))->latest()->paginate(20)->withQueryString();return Inertia::render('Users/Index',['users'=>$users,'filters'=>compact('search','status','role'),'roles'=>Role::query()->orderBy('name')->pluck('name'),'stats'=>['total'=>User::count(),'active'=>User::where('is_active',true)->count(),'suspended'=>User::where('is_active',false)->count(),'administrators'=>User::role('superadmin')->count()]]);}
public function create():Response{return Inertia::render('Users/Create',['roles'=>Role::query()->orderBy('name')->pluck('name')]);}
public function store(Request $request):RedirectResponse{$data=$request->validate(['name'=>['required','string','max:255'],'email'=>['required','email','max:255','unique:users,email'],'role'=>['required',Rule::exists('roles','name')->where('guard_name','web')],'password'=>['required','confirmed',Password::min(8)]]);$user=DB::transaction(function()use($data){$user=User::create(['name'=>$data['name'],'email'=>$data['email'],'password'=>$data['password'],'is_active'=>true,'email_verified_at'=>now()]);$user->assignRole($data['role']);return $user;});return to_route('users.index')->with('success',"Compte {$user->name} créé.");}
public function edit(User $user):Response{return Inertia::render('Users/Edit',['managedUser'=>$user->load('roles:id,name'),'roles'=>Role::query()->orderBy('name')->pluck('name')]);}
public function update(Request $request,User $user):RedirectResponse{$data=$request->validate(['name'=>['required','string','max:255'],'email'=>['required','email','max:255',Rule::unique('users','email')->ignore($user)],'role'=>['required',Rule::exists('roles','name')->where('guard_name','web')],'is_active'=>['required','boolean'],'password'=>['nullable','confirmed',Password::min(8)]]);if($user->is($request->user())&&!$data['is_active'])throw ValidationException::withMessages(['is_active'=>'Vous ne pouvez pas suspendre votre propre compte.']);$isLastSuperadmin=$user->hasRole('superadmin')&&User::role('superadmin')->whereKeyNot($user->id)->count()===0;if($isLastSuperadmin&&($data['role']!=='superadmin'||!$data['is_active']))throw ValidationException::withMessages(['role'=>'Le dernier super administrateur doit rester actif et conserver son rôle.']);DB::transaction(function()use($user,$data){$attributes=['name'=>$data['name'],'email'=>$data['email'],'is_active'=>$data['is_active']];if(!empty($data['password']))$attributes['password']=$data['password'];$user->update($attributes);$user->syncRoles([$data['role']]);});return to_route('users.index')->with('success',"Compte {$user->name} mis à jour.");}
public function destroy(Request $request,User $user):RedirectResponse{if($user->is($request->user()))throw ValidationException::withMessages(['user'=>'Vous ne pouvez pas supprimer votre propre compte.']);if($user->hasRole('superadmin')&&User::role('superadmin')->whereKeyNot($user->id)->count()===0)throw ValidationException::withMessages(['user'=>'Le dernier super administrateur ne peut pas être supprimé.']);$references=[['student_cards','created_by'],['visits','checked_in_by'],['visits','checked_out_by'],['consultation_sessions','opened_by'],['consultation_sessions','closed_by'],['consultation_items','scanned_by'],['consultation_items','returned_by'],['imports','uploaded_by'],['imports','committed_by'],['loans','opened_by'],['loans','closed_by'],['loan_items','loaned_by'],['loan_items','returned_by']];foreach($references as[$table,$column])if(DB::table($table)->where($column,$user->id)->exists())throw ValidationException::withMessages(['user'=>'Ce compte possède un historique opérationnel. Suspendez-le pour conserver la traçabilité.']);$name=$user->name;$user->delete();return to_route('users.index')->with('success',"Compte {$name} supprimé.");}
}
