<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, router, useForm, usePage } from '@inertiajs/vue3';
import { ref } from 'vue';
defineProps<{categories:any[];authors:{data:any[]};locations:any[]}>();
const page=usePage();
const canDelete=page.props.auth.permissions.includes('catalog.manage');
const category=useForm({name:'',description:''});
const author=useForm({display_name:''});
const location=useForm({type:'shelf',number:'',name:'',description:''});
const editing=ref<{type:string;id:number;value:string}|null>(null);
const editingLocation=ref<any|null>(null);
const edit=(type:string,item:any)=>editing.value={type,id:item.id,value:type==='author'?item.display_name:item.name};
const save=()=>{if(!editing.value)return;const e=editing.value;const url=e.type==='category'?route('categories.update',e.id):route('authors.update',e.id);router.patch(url,e.type==='category'?{name:e.value}:{display_name:e.value},{onSuccess:()=>editing.value=null});};
const remove=(type:string,item:any)=>{if(!confirm(`Supprimer « ${item.name||item.display_name} » ?`))return;const url=type==='category'?route('categories.destroy',item.id):type==='author'?route('authors.destroy',item.id):route('locations.destroy',item.id);router.delete(url);};
const saveLocation=()=>{if(!editingLocation.value)return;router.patch(route('locations.update',editingLocation.value.id),editingLocation.value,{onSuccess:()=>editingLocation.value=null});};
</script>
<template><Head title="Référentiels"/><AuthenticatedLayout><template #header><div><p class="text-xs font-bold uppercase tracking-widest text-primary-600">Catalogue</p><h1 class="mt-1 font-heading text-2xl font-bold text-slate-800">Référentiels</h1><p class="mt-2 text-sm text-slate-500">Catégories, auteurs et rangement physique de la bibliothèque.</p></div></template><div v-if="$page.props.flash?.success" class="mb-5 rounded-md bg-emerald-50 p-3 text-sm text-emerald-700">{{$page.props.flash.success}}</div><div v-if="Object.keys($page.props.errors||{}).length" class="mb-5 rounded-md bg-red-50 p-3 text-sm text-red-700">{{Object.values($page.props.errors||{})[0]}}</div><div class="grid gap-6 xl:grid-cols-3">
<section class="dw-card p-5"><h2 class="font-heading font-bold text-slate-800">Catégories</h2><form class="mt-4 flex gap-2" @submit.prevent="category.post(route('categories.store'),{onSuccess:()=>category.reset()})"><input v-model="category.name" class="dw-field" placeholder="Ex. Droit civil" required/><button class="rounded-md bg-primary-600 px-3 text-white">Ajouter</button></form><ul class="mt-4 divide-y divide-slate-100"><li v-for="item in categories" :key="item.id" class="py-3 text-sm"><form v-if="editing?.type==='category'&&editing.id===item.id" class="flex gap-2" @submit.prevent="save"><input v-model="editing.value" class="dw-field h-9"/><button class="text-xs font-bold text-primary-600">OK</button></form><div v-else class="flex items-center gap-2"><span class="min-w-0 flex-1 font-semibold">{{item.name}}</span><span class="text-xs text-slate-400">{{item.books_count}} ouvrage(s)</span><button class="text-xs font-bold text-amber-600" @click="edit('category',item)">Modifier</button><button v-if="canDelete" class="text-xs font-bold text-red-600" @click="remove('category',item)">×</button></div></li></ul></section>
<section class="dw-card p-5"><h2 class="font-heading font-bold text-slate-800">Auteurs</h2><form class="mt-4 flex gap-2" @submit.prevent="author.post(route('authors.store'),{onSuccess:()=>author.reset()})"><input v-model="author.display_name" class="dw-field" placeholder="Nom complet" required/><button class="rounded-md bg-primary-600 px-3 text-white">Ajouter</button></form><ul class="mt-4 divide-y divide-slate-100"><li v-for="item in authors.data" :key="item.id" class="py-3 text-sm"><form v-if="editing?.type==='author'&&editing.id===item.id" class="flex gap-2" @submit.prevent="save"><input v-model="editing.value" class="dw-field h-9"/><button class="text-xs font-bold text-primary-600">OK</button></form><div v-else class="flex items-center gap-2"><span class="min-w-0 flex-1 font-semibold">{{item.display_name}}</span><span class="text-xs text-slate-400">{{item.books_count}}</span><button class="text-xs font-bold text-amber-600" @click="edit('author',item)">Modifier</button><button v-if="canDelete" class="text-xs font-bold text-red-600" @click="remove('author',item)">×</button></div></li></ul></section>
<section class="dw-card p-5"><h2 class="font-heading font-bold text-slate-800">Armoires et étagères</h2><p class="mt-2 text-xs text-slate-400">Le code est généré automatiquement, par exemple ARM-1 ou ETA-2.</p><form class="mt-4 space-y-2" @submit.prevent="location.post(route('locations.store'),{onSuccess:()=>location.reset()})"><select v-model="location.type" class="dw-field"><option value="cabinet">Armoire</option><option value="shelf">Étagère</option><option value="other">Autre</option></select><input v-model="location.number" class="dw-field" placeholder="Numéro ou repère (ex. 1, A2)" required/><input v-if="location.type==='other'" v-model="location.name" class="dw-field" placeholder="Type de rangement" required/><button class="h-10 w-full rounded-md bg-primary-600 text-sm font-bold text-white">Ajouter l’emplacement</button></form><ul class="mt-4 divide-y divide-slate-100"><li v-for="item in locations" :key="item.id" class="py-3 text-sm"><form v-if="editingLocation?.id===item.id" class="space-y-2" @submit.prevent="saveLocation"><select v-model="editingLocation.type" class="dw-field h-9"><option value="cabinet">Armoire</option><option value="shelf">Étagère</option><option value="other">Autre</option></select><input v-model="editingLocation.number" class="dw-field h-9" required/><input v-if="editingLocation.type==='other'" v-model="editingLocation.name" class="dw-field h-9" required/><div class="flex gap-3"><button class="text-xs font-bold text-primary-600">Enregistrer</button><button type="button" class="text-xs text-slate-400" @click="editingLocation=null">Annuler</button></div></form><div v-else class="flex items-center gap-2"><span class="min-w-0 flex-1"><strong>{{item.name}}</strong><span class="ms-2 font-mono text-xs text-primary-600">{{item.code}}</span></span><span class="text-xs text-slate-400">{{item.copies_count}} ex.</span><button class="text-xs font-bold text-amber-600" @click="editingLocation={id:item.id,type:item.type,number:item.number||'',name:item.name,description:item.description||''}">Modifier</button><button v-if="canDelete" class="text-xs font-bold text-red-600" @click="remove('location',item)">×</button></div></li></ul></section>
</div></AuthenticatedLayout></template>
