<script setup lang="ts">
import AppIcon from '@/Components/AppIcon.vue'; import InputError from '@/Components/InputError.vue'; import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'; import {Head,Link,router,useForm,usePage} from '@inertiajs/vue3'; import {ref} from 'vue';
const props=defineProps<{locations:any[];filters:{search:string}}>(); const page=usePage(); const canCreate=page.props.auth.permissions.includes('locations.create'); const canUpdate=page.props.auth.permissions.includes('locations.update'); const canDelete=page.props.auth.permissions.includes('catalog.manage');
const form=useForm({type:'shelf',number:'',name:'',description:''}); const editing=ref<any|null>(null);
const create=()=>form.post(route('locations.store'),{onSuccess:()=>form.reset()}); const save=()=>editing.value&&router.patch(route('locations.update',editing.value.id),editing.value,{onSuccess:()=>editing.value=null}); const remove=(item:any)=>confirm(`Supprimer l’emplacement « ${item.name} » ?`)&&router.delete(route('locations.destroy',item.id));
const search=ref(props.filters.search); const find=()=>router.get(route('locations.index'),{search:search.value},{preserveState:true,replace:true});
</script>
<template><Head title="Emplacements"/><AuthenticatedLayout><template #header><div><Link :href="route('catalog-references.index')" class="text-xs font-bold text-primary-600">← Référentiels</Link><h1 class="dw-page-title">Emplacements</h1><p class="dw-page-description">Organisation physique des exemplaires dans les armoires et étagères.</p></div></template>
<div v-if="$page.props.flash?.success" class="mb-5 rounded-md bg-emerald-50 p-4 text-sm text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{{$page.props.flash.success}}</div><InputError class="mb-4" :message="$page.props.errors?.location"/>
<div class="grid gap-6 xl:grid-cols-[360px_1fr]"><section v-if="canCreate" class="dw-card self-start p-5"><h2 class="text-lg font-bold">Nouvel emplacement</h2><p class="mt-2 text-xs text-slate-400">Le code ARM, ETA ou AUT est généré automatiquement.</p><form class="mt-5 space-y-4" @submit.prevent="create"><div><label class="mb-2 block text-sm">Type *</label><select v-model="form.type" class="dw-field"><option value="cabinet">Armoire</option><option value="shelf">Étagère</option><option value="other">Autre</option></select></div><div><label class="mb-2 block text-sm">Numéro ou repère *</label><input v-model="form.number" class="dw-field" placeholder="Ex. 1 ou A2" required/><InputError :message="form.errors.number"/></div><div v-if="form.type==='other'"><label class="mb-2 block text-sm">Type de rangement *</label><input v-model="form.name" class="dw-field" required/></div><div><label class="mb-2 block text-sm">Description</label><textarea v-model="form.description" class="dw-field"/></div><button class="dw-btn-primary w-full">Ajouter l’emplacement</button></form></section>
<section class="dw-card overflow-hidden"><div class="border-b border-gray-200 p-5 dark:border-gray-900"><h2 class="text-lg font-bold">Armoires et étagères</h2><p class="mt-1 text-xs text-slate-400">{{locations.length}} résultat(s)</p></div><form class="flex gap-2 border-b border-gray-200 p-4 dark:border-gray-900" @submit.prevent="find"><div class="relative flex-1"><AppIcon name="search" class="absolute start-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input v-model="search" class="dw-field ps-10" placeholder="Rechercher par nom, code, type ou description…"/></div><button class="dw-btn-primary">Rechercher</button></form><div class="overflow-x-auto"><table class="dw-table min-w-[700px]"><thead><tr><th class="p-4 text-start">Emplacement</th><th class="p-4 text-start">Code</th><th class="p-4 text-start">Type</th><th class="p-4 text-center">Exemplaires</th><th class="p-4 text-center">Actions</th></tr></thead><tbody><tr v-for="item in locations" :key="item.id"><template v-if="editing?.id===item.id"><td class="p-4"><input v-if="editing.type==='other'" v-model="editing.name" class="dw-field h-9"/></td><td class="p-4 text-xs text-slate-400">Recalculé</td><td class="p-4"><select v-model="editing.type" class="dw-field h-9"><option value="cabinet">Armoire</option><option value="shelf">Étagère</option><option value="other">Autre</option></select></td><td class="p-4"><input v-model="editing.number" class="dw-field h-9" required/></td><td class="p-4"><div class="flex justify-center"><button class="h-9 w-9 text-emerald-600" @click="save"><AppIcon name="check" class="mx-auto h-4 w-4"/></button><button class="h-9 w-9 text-slate-400" @click="editing=null"><AppIcon name="close" class="mx-auto h-4 w-4"/></button></div></td></template><template v-else><td class="p-4"><strong class="text-slate-700 dark:text-white">{{item.name}}</strong><p class="mt-1 text-xs text-slate-400">{{item.description||'Sans description'}}</p></td><td class="p-4 font-mono text-xs font-bold text-primary-600">{{item.code}}</td><td class="p-4 capitalize">{{item.type==='cabinet'?'Armoire':item.type==='shelf'?'Étagère':'Autre'}}</td><td class="p-4 text-center">{{item.copies_count}}</td><td class="p-4"><div class="flex justify-center gap-1"><button v-if="canUpdate" class="h-9 w-9 text-amber-600" @click="editing={...item}"><AppIcon name="edit" class="mx-auto h-4 w-4"/></button><button v-if="canDelete" class="h-9 w-9 text-red-600" @click="remove(item)"><AppIcon name="trash" class="mx-auto h-4 w-4"/></button></div></td></template></tr><tr v-if="!locations.length"><td colspan="5" class="p-10 text-center text-slate-400">Aucun emplacement trouvé.</td></tr></tbody></table></div></section></div>
</AuthenticatedLayout></template>
